### ISSUE TITLE
Can not use docker vars / hostnames to link to the ES container

### ISSUE THREAD

**Issue by mikehaertl** [fabric8io/docker-kibana4#1]
I try to use your image with fig in a simple setup like this:

``` yaml
elk:
    image: pblittle/docker-logstash:latest
    volumes:
        - ./logstash/:/opt/logstash/conf.d
    ports:
        - "9292:9292"
        - "9200:9200"
    expose:
        - "9292"
        - "9200"
kibana:
    image: jimmidyson/kibana4:latest
    ports:
        - "5601:5601"
    links:
        - elk
    environment:
        ELASTICSEARCH_URL: "http://elk:9200"
```

Unfortunately this doesn't work. It fails with this error:

```
kibana_1 | {"@timestamp":"2015-02-24T18:53:36.173Z","level":"error","node_env":"production","error":"Request error, retrying -- connect ECONNREFUSED"}
kibana_1 | {"@timestamp":"2015-02-24T18:53:36.179Z","level":"warn","message":"Unable to revive connection: http://elk:9200/","node_env":"production"}
kibana_1 | {"@timestamp":"2015-02-24T18:53:36.179Z","level":"warn","message":"No living connections","node_env":"production"}
kibana_1 | {"@timestamp":"2015-02-24T18:53:36.184Z","level":"fatal","message":"No Living connections","node_env":"production","error":{"message":"No Living connections","name":"Error","stack":"Error: No Living connections\n  at sendReqWithConnection (/opt/kibana-4.0.0-linux-x64/src/node_modules/elasticsearch/src/lib/transport.js:174:15)\n  at next (/opt/kibana-4.0.0-linux-x64/src/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)\n  at process._tickCallback (node.js:442:13)\n"}}
```

I can't use a static IP either, as docker uses another IP on each `fig up` for the `elk` container.

Any hints how to make this work with fig?
